# Generated by Django 4.1.3 on 2022-11-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("0", "male"), ("1", "female"), ("2", "other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
