# Generated by Django 4.1.3 on 2022-11-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0001_initial"),
        ("users", "0004_alter_profile_height_alter_profile_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allergy",
            field=models.ManyToManyField(to="reference_information.allergy"),
        ),
    ]
