# Generated by Django 4.1.3 on 2022-11-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_profile_allergy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="allergy",
        ),
    ]
