# Generated by Django 4.1.3 on 2022-12-12 12:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0009_remove_profile_name_remove_profile_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="height",
            field=models.IntegerField(
                blank=True,
                help_text="in cm",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(300),
                    django.core.validators.MinValueValidator(40),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Username",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="weight",
            field=models.IntegerField(
                blank=True,
                help_text="in kg",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(650),
                    django.core.validators.MinValueValidator(2),
                ],
            ),
        ),
    ]
