# Generated by Django 4.1.3 on 2022-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Blood pressure"),
                            ("1", "Pulse"),
                            ("2", "Sugar level"),
                            ("3", "Height"),
                            ("4", "Weight"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("indicator_date", models.DateField()),
                ("indicator_time", models.TimeField(blank=True, null=True)),
                ("value", models.CharField(max_length=30)),
                ("comment", models.CharField(max_length=100)),
            ],
        ),
    ]
