# Generated by Django 4.1.3 on 2022-11-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "allergy_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Household allergens"),
                            ("1", "Pollen allergens"),
                            ("2", "Animal allergens"),
                            ("3", "Fungal allergens"),
                            ("4", "Insect allergens"),
                            ("5", "Food allergens"),
                            ("6", "Drug allergens"),
                            ("7", "Industrial allergens"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
