# Generated by Django 4.1.3 on 2022-11-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allergy",
            options={"verbose_name_plural": "Allergies"},
        ),
        migrations.AlterField(
            model_name="allergy",
            name="allergy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Household allergy"),
                    ("1", "Pollen allergy"),
                    ("2", "Animal allergy"),
                    ("3", "Fungal allergy"),
                    ("4", "Insect allergy"),
                    ("5", "Food allergy"),
                    ("6", "Drug allergy"),
                    ("7", "Industrial allergy"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
