# Generated by Django 4.1.3 on 2022-11-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0005_doctorspecialization"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Health tests",
            },
        ),
    ]
