# Generated by Django 4.1.3 on 2022-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0006_healthtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthtest",
            name="test_code",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
