# Generated by Django 4.1.3 on 2022-11-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0007_healthtest_test_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Med",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("address_1", models.CharField(max_length=300)),
                ("address_2", models.CharField(blank=True, max_length=300, null=True)),
                ("address_3", models.CharField(blank=True, max_length=300, null=True)),
                ("address_4", models.CharField(blank=True, max_length=300, null=True)),
                ("address_5", models.CharField(blank=True, max_length=300, null=True)),
                ("phone_1", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_2", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_3", models.CharField(blank=True, max_length=20, null=True)),
                ("site", models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                "verbose_name_plural": "Health tests",
            },
        ),
    ]
