# Generated by Django 4.1.3 on 2022-11-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0008_med"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Med",
            new_name="MedInstitution",
        ),
        migrations.AlterModelOptions(
            name="medinstitution",
            options={"verbose_name_plural": "Med institutions"},
        ),
    ]
