# Generated by Django 4.1.3 on 2022-11-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0009_rename_med_medinstitution_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("site", models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                "verbose_name_plural": "Laboratories",
            },
        ),
    ]
