# Generated by Django 4.1.3 on 2022-11-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0010_laboratory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Laboratory",
        ),
    ]
