# Generated by Django 4.1.3 on 2022-11-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visit_records", "0012_remove_appointment_examination_plan_and_more"),
        ("reference_information", "0014_doctor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HealthTest",
        ),
    ]
