# Generated by Django 4.1.3 on 2022-11-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0015_delete_healthtest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_code", models.CharField(default=0, max_length=10)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Analyzes",
            },
        ),
    ]
