# Generated by Django 4.1.3 on 2022-11-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0016_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="test_code",
            field=models.CharField(max_length=10),
        ),
    ]
