# Generated by Django 4.1.3 on 2022-11-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference_information", "0014_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateTimeField()),
                (
                    "reminder",
                    models.BooleanField(default=False, help_text="Create a reminder?"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Scheduled"), ("1", "Completed")], max_length=1
                    ),
                ),
                (
                    "examination_protocol",
                    models.TextField(
                        blank=True, help_text="Patient's complaints", null=True
                    ),
                ),
                (
                    "conclusion",
                    models.TextField(
                        blank=True, help_text="Diagnoses and health problems", null=True
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Treatment recommendations", null=True
                    ),
                ),
                ("file", models.FileField(upload_to="staticfiles/appointment_files")),
                (
                    "clinic",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference_information.medinstitution",
                    ),
                ),
                (
                    "diagnosis",
                    models.ManyToManyField(
                        related_name="appointment_diagnoses",
                        to="reference_information.diagnosis",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference_information.doctor",
                    ),
                ),
                (
                    "doctor_specialization",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference_information.doctorspecialization",
                    ),
                ),
                (
                    "examination_plan",
                    models.ManyToManyField(
                        blank=True,
                        related_name="appointment_tests",
                        to="reference_information.healthtest",
                    ),
                ),
                (
                    "med_category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference_information.medcategory",
                    ),
                ),
                (
                    "previous_appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit_records.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Appointments",
            },
        ),
    ]
