# Generated by Django 4.1.3 on 2022-11-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visit_records", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="doctor_specialization",
        ),
    ]
