# Generated by Django 4.1.3 on 2022-11-25 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit_records", "0002_remove_appointment_doctor_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="previous_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="visit_records.appointment",
            ),
        ),
    ]
