# Generated by Django 4.1.3 on 2022-11-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0014_doctor"),
        ("visit_records", "0006_appointmentdiagnosis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="diagnosis",
            field=models.ManyToManyField(
                related_name="appointment_diagnoses",
                to="reference_information.diagnosis",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="diagnosis",
            field=models.ManyToManyField(
                related_name="appointment_diagnoses",
                through="visit_records.AppointmentDiagnosis",
                to="reference_information.diagnosis",
            ),
        ),
    ]
