# Generated by Django 4.1.3 on 2022-11-29 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0014_doctor"),
        ("visit_records", "0007_alter_appointment_diagnosis"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentHealthTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit_records.appointment",
                    ),
                ),
                (
                    "health_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference_information.healthtest",
                    ),
                ),
            ],
        ),
    ]
