# Generated by Django 4.1.3 on 2022-11-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0014_doctor"),
        ("visit_records", "0008_appointmenthealthtest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="examination_plan",
            field=models.ManyToManyField(
                blank=True,
                related_name="appointment_tests",
                to="reference_information.healthtest",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="examination_plan",
            field=models.ManyToManyField(
                blank=True,
                related_name="appointment_tests",
                through="visit_records.AppointmentHealthTest",
                to="reference_information.healthtest",
            ),
        ),
    ]
