# Generated by Django 4.1.3 on 2022-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit_records", "0009_alter_appointment_examination_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="appointment_files/%Y/%m/%d"
            ),
        ),
    ]
