# Generated by Django 4.1.3 on 2022-11-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visit_records", "0011_alter_appointment_examination_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="examination_plan",
        ),
        migrations.DeleteModel(
            name="AppointmentHealthTest",
        ),
    ]
