# Generated by Django 4.1.3 on 2022-11-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_information", "0016_analysis"),
        ("visit_records", "0012_remove_appointment_examination_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference_information.analysis",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit_records.appointment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="analysis",
            field=models.ManyToManyField(
                blank=True,
                related_name="appointment_analyzes",
                through="visit_records.AppointmentAnalysis",
                to="reference_information.analysis",
            ),
        ),
    ]
